# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 05:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blood_donors', '0003_initial_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donatore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_tessera', models.CharField(max_length=255)),
                ('num_tessera_cartacea', models.CharField(blank=True, max_length=255)),
                ('data_rilascio_tessera', models.DateField(blank=True, null=True)),
                ('cognome', models.CharField(max_length=255)),
                ('nome', models.CharField(max_length=255)),
                ('codice_fiscale', models.CharField(blank=True, max_length=255)),
                ('data_nascita', models.DateField(blank=True, null=True)),
                ('data_iscrizione', models.DateField(blank=True, null=True)),
                ('gruppo_sanguigno', models.CharField(max_length=10)),
                ('rh', models.CharField(max_length=10)),
                ('fenotipo', models.CharField(blank=True, max_length=10)),
                ('kell', models.CharField(blank=True, max_length=10)),
                ('indirizzo', models.CharField(blank=True, max_length=255)),
                ('frazione', models.CharField(blank=True, max_length=255)),
                ('cap', models.CharField(blank=True, max_length=10)),
                ('citta', models.CharField(blank=True, max_length=255)),
                ('provincia', models.CharField(blank=True, max_length=100)),
                ('tel', models.CharField(blank=True, max_length=255)),
                ('tel_lavoro', models.CharField(blank=True, max_length=255)),
                ('cell', models.CharField(blank=True, max_length=255)),
                ('fax', models.CharField(blank=True, max_length=255)),
                ('email', models.CharField(blank=True, max_length=255)),
                ('fermo_per_malattia', models.BooleanField(default=False)),
                ('donazioni_pregresse', models.IntegerField(default=0)),
                ('num_benemerenze', models.IntegerField(default=0)),
                ('centro_raccolta_default', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blood_donors.CentroDiRaccolta')),
                ('sesso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blood_donors.Sesso')),
                ('sezione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blood_donors.Sezione')),
                ('stato_donatore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blood_donors.StatoDonatore')),
            ],
            options={
                'verbose_name_plural': 'Donatori',
            },
        ),
        migrations.AlterUniqueTogether(
            name='donatore',
            unique_together=set([('sezione', 'num_tessera')]),
        ),
    ]
