# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 05:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blood_donors', '0004_add_donatori'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donazione',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('centro_di_raccolta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blood_donors.CentroDiRaccolta')),
                ('donatore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blood_donors.Donatore')),
                ('tipo_donazione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blood_donors.TipoDonazione')),
            ],
            options={
                'verbose_name_plural': 'Donazioni',
            },
        ),
    ]
